Задание t-8 Pandas
		     1)	 Работа с Excel. С помощью библиотеки pandas написать программу …  (для отладки оставить в файле не более 10 строк, убрать лишние колонки, заменить значения так, чтобы легче проверять результат) 
см. https://datagy.io/pandas-groupby/
https://newtechaudit.ru/gruzi-daty-krasivo/
Моя шпаргалка по pandas / Хабр (habr.com)  10. Агрегирование
Файл с продажами   XLSX/Sample-sales-data-excel.xlsx 
   Row ID;Order ID;Order Date;Ship Date;Ship Mode;Customer ID;Customer Name;Segment;Country;City;State;Postal Code;Region;Product ID;Category;Sub-Category;Product Name;Sales;Quantity;Discount;Profit

получения из этой таблицы о суммарных продажах продукта указанного кода по каждому региону. Строки таблицы упорядочить по возрастанию сумм.

In [1]:
import pandas as pd

In [2]:
df = pd.read_excel("Sample-sales-data-excel.xlsx")

In [6]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [25]:
#указываем код продукта
product_id = "FUR-TA-10000577"

In [26]:
df.loc[df['Product ID'] == product_id].groupby('Region')['Sales'].sum().sort_values()

Region
East       1044.630
South      1149.093
Central    2193.723
West       2855.322
Name: Sales, dtype: float64